version: '3'

services:
  lambda:
    build: .
    environment:
      - PYTHONPATH=/var/task/src:/var/task/lib
      - PATH=/var/task/bin
      - AWS_BUCKET_NAME='cost-and-usage-bucket-boi'
      - AWS_ACCESS_KEY_ID='AKIAINNOZLSUV2XHNGWQ'
      - AWS_SECRET_ACCESS_KEY='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'
    volumes:
      - ./src/:/var/task/src/
